name: Run External Worflows and Wait
on:
  push
  
jobs:
  Trigger-Repos:
    runs-on: ubuntu-latest
    steps:
      - name: Run action
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: OneTrueRelaxed
          repo: dependant_repo
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow_file_name: main.yml
          wait_interval: 5
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true

      - name: Run action on another repo
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: OneTrueRelaxed
          repo: dependant_repo1
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow_file_name: main.yml
          wait_interval: 5
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
          
      - name: Invoke workflow with inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Do Something
          repo: OneTrueRelaxed/dependant_repo
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
