name: Run External Worflows and Wait
on:
  push
  
jobs:
  Trigger-Repos:
  runs-on: ubuntu-latest
- uses: convictional/trigger-workflow-and-wait@v1.3.0
  with:
    owner: OneTrueRelaxed
    repo: dependant_repo
    github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    workflow_file_name: main.yml
    wait_interval: 5
    propagate_failure: true
    trigger_workflow: true
    wait_workflow: true
